Phi: 18.925239728324588
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 0.5
beta: 5.016510268342619
center_lr_multiplier: 1.0
config_version: hyper3003_sub03_fit-human
from_logits: true
lr: 0.599354376562564
num_clusters: 8
num_repetitions: 16
num_subs: 23
q: 1
r: 2
random_seed: 999
specificity: 0.6995656905920985
temp1: equivalent
temp2: 0.6061033580050695
thr: 0.6029560079917686
trainable_specificity: false
unsup_rule: threshold
