Phi: 12.11123315982806
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 1.0
beta: 5.5402201701854406
center_lr_multiplier: 1.0
config_version: hyper2594_sub17_fit-human
from_logits: true
lr: 0.7042656164546285
num_clusters: 8
num_repetitions: 16
num_subs: 23
q: 1
r: 2
random_seed: 999
specificity: 0.3022568635159911
temp1: equivalent
temp2: 0.8031871418127604
thr: 0.4546590976804991
trainable_specificity: false
unsup_rule: threshold
