Phi: 14.060675848742004
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: sumtoone
attn_lr_multiplier: 5.0
beta: 0.5001300089475098
center_lr_multiplier: 1.0
config_version: hyper2855_sub13_fit-human
from_logits: true
lr: 1.3040005348872532
num_clusters: 8
num_repetitions: 16
num_subs: 23
q: 1
r: 2
random_seed: 999
specificity: 0.0005393616630177123
temp1: equivalent
temp2: 0.11235971997560394
thr: 0.2537846103114479
trainable_specificity: false
unsup_rule: threshold
