Phi: 11.0
actv_func: softmax
asso_lr_multiplier: 1.0
attn_constraint: nonneg
attn_lr_multiplier: 1.0
beta: 5.0
center_lr_multiplier: 1.0
config_version: hyper1274_general
from_logits: true
lr: 0.1
num_blocks: 32
num_clusters: 8
num_runs: 10
q: 1
r: 2
random_seed: 999
specificity: 1.1
temp: 0.012
thr: -0.5
trainable_specificity: false
unsup_rule: threshold
